java={'푸','피글렛','티거'}
python=set(['푸','이요르'])
# print(java&python)
# print(java.intersection(python))
# print(java|python)
# print(java.union(python))
# print(java-python)
# print(java.difference(python))
python.add('피글렛')
# print(python)
java.remove('피글렛')
print(java)